MapsPeople/web-ui

- packages/map-template/src/components/Search/Search.jsx
- packages/map-template/src/components/Wayfinding/Wayfinding.jsx
- packages/map-template/src/components/WebComponentWrappers/Search/Search.jsx
- Use web component wrappers for searching and category handling.
- Refactored `WebComponentWrappers/Search` to utilize `useImperativeHandle` in order to programmatically trigger methods on the `<mi-search>` component without relying on props.
- Introduced category prop on `WebComponentWrappers/Search` so we can filter by a category.
- Refactored the `Search` component to use the `WebComponentWrappers/Search` instead of `<mi-search>` directly.
- This had the benefits of
- removing some usages of `document.createElement` and native DOM event listeners
- getting rid of "double" variable for holding the selected category.
- Refactored the `Wayfinding` component to make use of the imperative ways to trigger method on the `WebComponentWrappers/Search` component.
> Use web component wrapper components for search & categories

- packages/components/src/components.d.ts
- packages/components/src/components/list-item-location/list-item-location.tsx
- packages/components/src/components/list-item-location/readme.md
- packages/components/src/components/list-item-location/test.html
- packages/map-template/src/components/Search/Search.jsx
- packages/map-template/src/components/WebComponentWrappers/ListItemLocation/ListItemLocation.jsx
- Fix bug where imageURL on a Locations was wrongly populated with icon from Display Rule when having a Location displayed as part of a search result.
- Implement new (optional) icon prop on the Stencil component `<mi-list-item-location>`
- The component will fallback to current behavior if not set, thus ensuring backwards comparability.
- This required some refactoring of the Live Data badge handling
- Set the icon prop within the wrapper component `ListItemLocation` instead of overwriting the Location data in the `Search` component.
> Fix/avoid replacing imageurl on location.details

- packages/map-template/src/components/Wayfinding/Wayfinding.jsx
- Fix issue of not showing directions when switching between origin and destination 
- Set the error messages to not be shown by default when calculating the directions, which was causing the `switch` button to not show any directions because the state was kept as having an error message, and has never been set to `false`.
> Bugfix/ switch directions

- packages/map-template/src/components/BottomSheet/BottomSheet.jsx
- packages/map-template/src/components/Sidebar/Sidebar.jsx
- packages/map-template/src/components/Wayfinding/Wayfinding.jsx
- Fix a bug where the `currentLocation` would always persist when going back from Directions to the Wayfinding view.
- Avoid mixing `currentLocation` and `directionsToLocation` in the `to` prop on the Wayfinding component.
> Fix for wrong Location shown in the search field after having requested directions

- packages/map-template/src/components/Directions/Directions.jsx
- Fix bug where the left padding for directions on the map was wrongly calculated
- The padding should be the width of the sidebar + padding. It had nothing to do width the width of the map container.
- Also renamed functions for more clarity.
> Fx wrong calculation of directions padding on larger screens.

- packages/map-template/src/App.jsx
- packages/map-template/src/components/Map/Map.jsx
- packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx
- Show the location on the map when setting the `locationId` property 
- Center the map and zoom in until level 21
- Handle the cases when the `locationId` belongs to a different venue
- Handle the cases when the `locationId` is on a different floor than the default one 
- Pass down the `locationId` property to the `Map` component 
- Resolve the promise instead of fitting the map to the venue when having the `locationId` property set
- Handle the floor selector, the centering of the map and the zooming on the location inside the `building_changed` event listener 
- Set the current venue to be the one that the `locationId` belongs to
> Show the location on the map when setting the "locationId" prop

- package-lock.json
- packages/map-template/package.json
- Bump the version of the Map Template package.
- We need the latest changes published as a release candidate to NPM.
> Version update for release candidate 2 on NPM

- .github/workflows/components-bump-version-release.yml
- packages/components/package.json
- packages/components/release.sh
Files are based on a test repo here:
- https://github.com/markhougaard/github-workflow-test/blob/main/packages/components/package.json
- https://github.com/markhougaard/github-workflow-test/blob/main/packages/components/release.sh
- https://github.com/markhougaard/github-workflow-test/blob/main/.github/workflows/components-bump-version.yml
See tags in the test repo here:
- This run: https://github.com/markhougaard/github-workflow-test/actions/runs/5084733450/jobs/9137391524 created this tag: https://github.com/markhougaard/github-workflow-test/releases/tag/components-v33.1.0.
Tested it with the other workspace/package as well: https://github.com/markhougaard/github-workflow-test/actions/runs/5084940648/jobs/9137862560#step:6:29
All of this is because of this bug in the npm-cli: …
> Components: Use shell script when triggering release

- .github/workflows/components-bump-version-release.yml
- packages/map-template/package.json
@andreeaceachir142 @ammapspeople I missed a spot, so it actually didn't run the right `release` command when we merged in earlier today. It means that we didn't tag the commit correctly, but I can do that retroactively. Also, as a side-effect, now we have the world's largest `changelog.md` file, so something good came out of it.
If we label this PR, we'll release new versions of both Components and Map Template, and I'm unsure if we want that because of some internal build process updates.
> Update build workflows

- packages/map-template/src/App.jsx
- packages/map-template/src/components/BottomSheet/BottomSheet.jsx
- packages/map-template/src/components/BottomSheet/Sheet/Sheet.jsx
- packages/map-template/src/components/Search/Search.jsx
- packages/map-template/src/components/Search/Search.scss
- Resize the search view when no categories are shown 
- Add a check if the preferredSizeSnapPoint is undefined and do not set the height of the sheet if that is the case
- Conditionally render the categories if they exist 
- Adjust the styles and the heights of the elements in order to fit the view they need to be rendered in
> Resize the search view when no categories are shown

- packages/map-template/src/components/Directions/Directions.scss
- Fix issue of closing button not being clickable due to long location name 
- Calculate the width of the locations info and subtract the width of the closing button in order to avoid overlapping content
> Calculate width of location text based on closing button

- packages/map-template/src/components/Map/Map.jsx
- Add support for the `startZoomLevel` to take priority over the `locationId` when present 
- Add a check for the existence of the `startZoomLevel` when zooming into the `locationId`
- If `startZoomLevel` is present, then the map should not zoom to the max zoom level on the selected location
> Add support for "startZoomLevel" to take priority over "locationId" 

- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/Search/Search.jsx
- packages/map-template/src/components/Search/Search.scss
- Show the error message when no results are found on the search page 
- Move the error message outside of the search results list container, which is conditioned to be shown only when having search results
> Show error message on the search page

- packages/map-template/.github/README.md
- packages/map-template/deploy-to-gcloud.sh
- packages/map-template/package.json
To test this, run the following commands in a shell:
```
$ cd package/map-template
$ npm run deploy-to-gcloud
```
This will fail, because no argument is given.
In the same folder:
```
$ npm run deploy-to-gcloud -- BUCKET_NAME
```
If you have the rights to deploy to that bucket, it will succeed. If not, it will fail.
> Add "deploy-to-gcloud" script

- packages/map-template/.github/README.md
- packages/map-template/deploy-to-gcloud.sh
Reading up on the docs for `gsutil`'s `cp` function, the change now uploads the contents correctly.
> Copy correct build path

- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/Sidebar/Modal/Modal.scss
- Fix visibility of multiple modals shown at the same time.
- Use the css `display` property in order to only show the active modal.
> Fix visibility of multiple modals 

- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/Wayfinding/Wayfinding.jsx
- Change error message on the wayfinding page.
- Remove the error state and only show the `No route found` error message in both scenarios.
> Change error message on the Wayfinding page

- packages/components/CHANGELOG.md
- packages/components/src/components/my-position/my-position.scss
The `mi-my-position` button is hard to style and is sometimes hiding behind other elements - most often behind the `mi-floor-selector`.
I removed the `position: absolute` styling from this component.
> My position button is sometimes hidden behind floor selector

- packages/components/CHANGELOG.md
- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/Directions/Directions.jsx
- packages/map-template/src/components/Search/Search.jsx
- packages/map-template/src/helpers/SetMapZoomLevel.js
- packages/map-template/src/hooks/useLocationForWayfinding.js
- Replace mapsindoors global variable
- A previous merge which took care of loading the MapsIndoors JS SDK if not available changed the way we use the mapsindoors, and we had to replace the instances where the global variable was used. Some of the instances were not changed and therefore threw errors 
- Remove all the global variables for the `window.mapsindoors`
> Replace mapsindoors global variable

- packages/components/CHANGELOG.md
- packages/components/src/components.d.ts
- packages/components/src/components/location-info/location-info.tsx
- packages/components/src/components/location-info/readme.md
I created a property with default value of 'Level'.
When we bind to it inside kiosk we will pipe it through translation for languages that we support with translations.
> MIAJS-1748 feature/matb: Add 'Level' word translation

- packages/map-template/src/components/Directions/Directions.jsx
- packages/map-template/src/components/RouteInstructions/RouteInstructions.jsx
refactor: move away from storing map center and zoom level in order to reset bounds when going back from destination step. Instead, trigger the SDK to refit the bounds.
> Substeps timing issue when going back from last step.

- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/Sidebar/Modal/Modal.scss
- Fix scrollable list not respecting the height on Safari
- Remove the `min-height` property from the modal, which Safari interprets differently than other browsers
- Tested it on other browsers as well and it works as intended
> Fix scrollable list on Safari

- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/MapTemplate/MapTemplate.scss
- Hide floor selector when directions are open
- Due to the refactoring of the floor selector in the SDK, the class has been changed from `floor-selector` to `mi-floor-selector`, therefore the styling has been lost because the SCSS file has not been updated with the new class
> Hide floor selector when directions are open

- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/Map/Map.jsx
- Fix `startZoomLevel` property not working on Google Maps
- The use of `startZoomLevel` on a Google Maps map was not working and it threw the error: `InvalidValueError: setZoom: not a number`
- After some investigation on the error that was being thrown, I converted the `startZoomLevel` value into an integer when setting the zoom of the map using the `parseInt()` method.
> Fix startZoomLevel property not working on Google Maps

- packages/map-template/.github/README.md
- packages/map-template/CHANGELOG.md
- packages/map-template/README.md
- packages/map-template/releaseTools/webcomponent.js
- packages/map-template/src/atoms/gmMapIdState.js
- packages/map-template/src/components/Map/GoogleMapsMap/GoogleMapsMap.jsx
- packages/map-template/src/components/MapTemplate/MapTemplate.jsx
- packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx
- Add support for Google Maps Map ID prop
- Pass the new `gmMapId` prop to the `GoogleMapsMap.jsx` inside the `mapViewOptions` object
> Add support for Google Maps Map ID prop

- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/Map/Map.jsx
- Refactor usage of `clear` function on localStorage
- Use the `removeItem` function instead of the `clear` function
> Refactor usage of clear function on localStorage

- packages/map-template/src/components/WebComponentWrappers/Search/Search.jsx
- Fixed search throwing console error
- Refactor the call for the `changed` function on the Search Wrapper Component.
> Fixed search throwing console error

- packages/map-template/CHANGELOG.md
- packages/map-template/README.md
- packages/map-template/src/components/BottomSheet/BottomSheet.scss
- packages/map-template/src/index.css
- Fix bottom sheet not being fully visible when running on a deployed version
- Use a new CSS property called `svh` instead of `vh` which takes the smallest viewport height
> Fix bottom sheet not being fully visible 

- packages/map-template/README.md
Fix wrong imports in the Readme file for the Map Template. Imports cannot contain tags. Those should be used when installing.
> Fix broken imports in Map Template readme

- packages/map-template/CHANGELOG.md
- packages/map-template/releaseTools/webcomponent.js
- packages/map-template/src/atoms/currentKioskLocationState.js
- packages/map-template/src/atoms/kioskOriginLocationIdState.js
- packages/map-template/src/components/Directions/Directions.jsx
- packages/map-template/src/components/Map/Map.jsx
- packages/map-template/src/components/MapTemplate/MapTemplate.jsx
- packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx
- packages/map-template/src/components/Search/Search.jsx
- packages/map-template/src/components/Sidebar/Modal/Modal.jsx
- packages/map-template/src/components/Sidebar/Modal/Modal.scss
- packages/map-template/src/helpers/GetDesktopPadding.js
- packages/map-template/src/helpers/GetDesktopPaddingBottom.js
- packages/map-template/src/helpers/GetDesktopPaddingLeft.js
- packages/map-template/src/helpers/GetMobilePaddingBottom.js
- packages/map-template/src/helpers/fitBoundsLocation.js
- Implement kioskOriginLocationId prop 
- Center the sidebar instead of having it placed in the left side
- Use the `fitBounds` function when having both `kioskOriginLocationId` and `locationId` props
- Restrict the kiosk to only be on desktop devices
- Create a new function `fitBoundsLocation` which is reused in three different places
- Refactor the `onLocationIdChanged` function to happen in a `useEffect`, and make sure the map is ready at the time the changes are happening 
- Handle both the `kioskOriginLocationId` and the `locationId` in the same `useEffect`
- Create helper functions for getting the desktop padding to the left and bottom, and the mobile padding to the bottom
- Do not allow location selection or clicking the location if it's the `kioskOriginLocationId` (meaning that it …
> Implement kioskOriginLocationId prop

- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/Map/Map.jsx
- packages/map-template/src/components/Search/Search.jsx
- packages/map-template/src/helpers/fitBoundsLocation.js
- Add support for `startZoomLevel`, `pitch` and `bearing` to be working in combination with locationId and kioskOriginLocationId
- In the `fitBoundsLocation()` function, when calling the `fitBounds()` from the SDK, handle the presence of startZoomLevel, pitch and bearing properties.
- Add the additional 3 props when calling `fitBoundsLocation()` when having the `locationId` and `kioskOriginLocationId` props
> Add support for startZoomLevel, pitch and bearing working in combination with other props

- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/VenueSelector/VenueSelector.jsx
- packages/map-template/src/hooks/useMapBoundsDeterminer.js
- Fix bug where (when using `kioskOriginLocationId`) clicking on a search result not belonging to the currently set venue would not pan the map to the clicked Location, but instead reset the map to the initial settings.
- Made the `useMapBoundsDeterminer` hook react to changes in the "venue" prop instead of the internal `venueName` state. Also manually trigger map pan when using the Venue Selector, since the responsibility of doing that was previously mistakenly given to the `useMapBoundsDeterminer` hook.
> Fix: Pan the map to correct location when clicking on search result not belonging to the current venue

- package-lock.json
- packages/components/CHANGELOG.md
- packages/components/src/components/my-position/my-position.tsx
- Fix issue of map resetting the tilt when having the position enabled 
- Remove call for resetting the tilt when having the position enabled but untracked
> Remove call for resetting the tilt when having an untracked position

- package-lock.json
- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/QRCodeDialog/QRCodeDialog.jsx
- Fix the issue of having incomplete URL when scanning the QR code
- Combine the `origin` and `pathname` when creating the targetURL
> Fix error when scanning the QR code

- packages/map-template/CHANGELOG.md
- packages/map-template/src/hooks/useReset.js
- Fixed search results not being reset when using the timeout property 
- Add the `searchResults` to the `useReset` hook
> Search results state is not reset when using the timeout property

- packages/map-template/CHANGELOG.md
- packages/map-template/src/hooks/useReset.js
- Fix accessibility not resetting when using the timeout property 
- Add the `accessibilityOn` state on the `useReset` hook
> Accessibility not resetting when using the timeout property

- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/Search/Search.jsx
- packages/map-template/src/components/WebComponentWrappers/Search/Search.jsx
- Add support for searching for locations which are in the same venue in the kiosk mode
- Add `mi-venue` attribute to the `mi-search` component which checks if kiosk we are in kiosk mode
- Add `venue` attribute when getting the filtered locations after clicking on a location 
- Add the `venueId` from the kiosk location to both instances
> Add support for searching within the same venue in kiosk mode

- package-lock.json
- packages/map-template/.github/README.md
- packages/map-template/CHANGELOG.md
- packages/map-template/README.md
- packages/map-template/releaseTools/webcomponent.js
- packages/map-template/src/atoms/miTransitionLevelState.js
- packages/map-template/src/components/Map/MapboxMap/MapboxMap.jsx
- packages/map-template/src/components/MapTemplate/MapTemplate.jsx
- packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx
- Add support for `miTransitionLevel` on Mapbox
- Create a new parameter for `miTransitionLevel`
- Add the parameter to the `webcomponent.js`
- Handle the parameter and check if it's a number
- Default to 17 if it's not a number
> Add support for MapsIndoors Transition Level

- package-lock.json
- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/Map/Map.jsx
- packages/map-template/src/components/WebComponentWrappers/ListItemLocation/ListItemLocation.jsx
- Remove hover from non-selectable locations 
- Implement functionality for checking if the location is non-selectable before calling the `hoverLocation()` and `unhoverLocation()` on the `ListItemLocation.jsx` file
- Implement functionality for detecting the hovered locations on the map, and if the location is non-selectable, call the `unhoverLocation()`
> Remove hover from non-selectable locations

- package-lock.json
- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/LocationDetails/LocationDetails.scss
- Fix size of the images on the Location Details prop
- Based on UX considerations, removed the `aspect-ratio`, changed the `object-fit` to `contain` and added a padding of `16px` at the top and bottom of the image.
> Fix size of the images on the Location Details page

- package-lock.json
- packages/map-template/CHANGELOG.md
- packages/map-template/releaseTools/webcomponent.js
- packages/map-template/src/components/MapTemplate/MapTemplate.jsx
- packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx
- packages/map-template/src/components/Search/Categories/Categories.jsx
- packages/map-template/src/components/Search/Search.jsx
- packages/map-template/src/helpers/GetActiveCategory.js
- Add support for category property 
- Add new property called `category`
- Check if the category prop exists in the list of sorted categories -> if it exists, then set the `selectedCategory` atom 
- Use `MutationObserver` to detect when the active chip element appears on the map 
- Scroll into the view of the active category 
**Note!** Remember that the category property should be the Key (Administrative ID) and not the Display name.
> Add support for category property

- package-lock.json
- packages/map-template/.gitignore
- packages/map-template/CHANGELOG.md
- packages/map-template/package.json
- packages/map-template/src/App.jsx
- packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx
- packages/map-template/src/components/SplashScreen/SplashScreen.jsx
- packages/map-template/src/index.jsx
- packages/map-template/vite.config.js
Adding support for Sentry Error Logging, Release Tracking, and Application Performance Monitoring.
One big thing that makes the Map Template deviate from the standard Sentry docs is that we don't use React Routes, but keep everything on `/` as a single-page app. We can do profiling of individual components, and that might give us more insight into which ones are heavy/slow, or other bottlenecks they might create. Docs here: https://docs.sentry.io/platforms/javascript/guides/react/features/component-tracking/. I haven't seen a named Component automatically tracked, besides the one [I made myself](https://github.com/MapsPeople/web-ui/pull/343#pullrequestreview-1914170685), so we need to go in and name all of the components.
> Add Sentry performance monitoring

- .github/workflows/bump-version-release.yml
- packages/components/package.json
- packages/map-template/README.md
- packages/midt/package.json
We could just go ahead and use jsDelivr as the CDN, but it caches even the `@latest` version very hard, and that would be a problem for us (it can take up 7 days before it's updated).
Including a workflow step to purge the CDN, we should see better results than using unpkg as the CDN, and hopefully don't run into trouble with files that are cached for too long.
> Use jsDelivr as CDN for Map Template Web Component

- package-lock.json
- packages/map-template/.github/README.md
- packages/map-template/CHANGELOG.md
- packages/map-template/README.md
- packages/map-template/releaseTools/webcomponent.js
- packages/map-template/src/atoms/searchAllVenues.js
- packages/map-template/src/components/MapTemplate/MapTemplate.jsx
- packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx
- packages/map-template/src/components/Search/Search.jsx
- packages/map-template/src/components/WebComponentWrappers/Search/Search.jsx
- Add support for searching in the same venue by default 
- Add new parameter called `searchAllVenues` which is a boolean that can be set in order to perform search across all venues in a solution 
- Fix issue with categories not updating when changing the venue
- Add new boolean parameter `searchAllVenues` and create an atom for storing the value
- Rename the `currentVenueName` for consistency reasons 
- In the `Search.jsx` file in the wrapper component, add a check if the `searchAllVenues` prop is true in the `mi-venue`
- In the `Search.jsx` file, add the venue attribute when searching for selecting a category in order to get the filtered locations 
- Add a new `useEffect()` on the `MapTemplate.jsx` file which handles the changes in the `currentVenueName` atom, and gets the current …
> Add support for searching in the same venue by default

- package-lock.json
- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/Map/Map.jsx
- packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx
- Fix the issue of current venue name not changing from the default venue 
- Changed the `AUSTIN` to the correct default venue `AUSTINOFFICE`
- Added the `setCurrentVenueName` when the venue is changed on the map
> Add current venue name when venue has changed on map

- packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx
We're hitting the rate limit, and don't use it much at this moment anyway.
> Disable Sentry replays

- package-lock.json
- packages/map-template/.github/README.md
- packages/map-template/CHANGELOG.md
- packages/map-template/README.md
- packages/map-template/releaseTools/webcomponent.js
- packages/map-template/src/atoms/hideNonMatchesState.js
- packages/map-template/src/components/Map/Map.jsx
- packages/map-template/src/components/MapTemplate/MapTemplate.jsx
- packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx
- Add a new property named `hideNonMatches` to switch between the "highlight" and "filter" methods on the SDK
- Add a new boolean prop `hideNonMatches`
- If set to `true`, the results will be filtered, otherwise hilghlighted
> Add property to switch between the "highlight" and "filter" methods on the SDK

- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/MapTemplate/MapTemplate.jsx
**What**
Don't use the whole IETF language string when setting the MapsIndoors SDK language.
**Why**
The SDK/backend does not work properly when using the whole IETF language string. Eg. using `es-co` will cause the fetched data to fallback to the default language, since it is only possible to define translations for `es` in the MapsIndoors platform.
**How**
Only use the first part of the language string, eg. `es` or `en` when calling `setLanguage()`. Now when eg. using a browser with the language set to `es-co`, it will instruct the SDK to set the language as `es`, which corresponds better with the data.
> Don't use the whole IETF language string when setting the MapsIndoors SDK language

- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/MapTemplate/MapTemplate.jsx
How:
- I simply assigned uniqueCategories to all categories that are active in the CMS and that exist.
- I performed a sorting method on the array. Order is dictated by the CMS. We can do it by finding the index.
> Fix category order in the MT

- packages/components/src/components/dropdown/dropdown.scss
- packages/components/src/components/dropdown/dropdown.tsx
- packages/components/src/components/dropdown/test.html
- Styling the disabled dropdown items inside a dropdown list.
- There was no visual representation for disabled options inside the dropdown elements.
- When rendering the list items, I decide what class list items get based on their disabled state.
> Disabled style for dropdown items

- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/Wayfinding/Wayfinding.jsx
- packages/map-template/src/components/Wayfinding/Wayfinding.scss
- packages/map-template/src/hooks/useDirectionsInfo.js
What: 
Disable 'Go' button if directions are not populated.
How: 
Created a simple boolean that is false when we start fetching data.
When data is populated, the boolean is set to true.
Applied specific styling for disabled button.
Working example:
https://github.com/MapsPeople/web-ui/assets/56337591/65377719-32f7-4763-b234-b8747877aaa7
PS. Talking to @andreeaceachir142, I removed two input fields for the time data is being fetched.
> Disable go button when directions are not populated

- package-lock.json
- packages/map-template/CHANGELOG.md
- packages/map-template/package.json
- packages/map-template/src/components/MapTemplate/MapTemplate.jsx
I upgraded SDK and Mapbox versions
> chore: upgrade Mapbox and Web SDK versions

- packages/map-template/CHANGELOG.md
- packages/map-template/src/selectors/currentPitch.js
- Fix bug where pitch property was not respected in case 2D/3D switch was not activated.
- Make sure always to default to the set pitch state, instead of undefined in case there is no Mapbox view mode.
> Fix bug where pitch property didnt work when 2d/3d switch was not shown

- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/Directions/Directions.jsx
When setting a route on the DirectionsRenderer, wait for setRoute to resolve before setting the step index. The setRoute method recently became asynchronous, meaning that the step index would be reset to -1 just before resolving, causing a mismatch in which step is active.
> Bugfix for wayfinding skipping first step

- packages/components/CHANGELOG.md
- packages/components/src/components.d.ts
- packages/components/src/components/dropdown/dropdown.tsx
- packages/components/src/components/dropdown/readme.md
Added cleared emitter so we can listen in the CMS when black X button is used.
> Add cleared event emitter to dropdown component

- packages/react-components/src/App.jsx
- packages/react-components/src/components/MIMap/MIMap.jsx
Expose the MapsIndoors instance as a function prop and showcase that it works in the test app by setting up a MI click event listener.
> Map as standalone component: Expose MapsIndoors instance

- packages/map-template/.github/README.md
- packages/map-template/CHANGELOG.md
Cleaned up the README file which is displayed on the GitHub page and removed all the duplicate code for props and query parameters. With this change, we avoid maintaining two separate README files. 
Instead, a link to NPM has been shared which can be accessed to see all the props and query parameters.
> Simplify README files

- packages/react-components/src/components/MIMap/GoogleMapsMap/GoogleMapsMap.jsx
- packages/react-components/src/components/MIMap/MIMap.jsx
- packages/react-components/src/components/MIMap/MapboxMap/MapboxMap.jsx
- Implement three new props on the MIMap component: `bounds`, `bearing` and `pitch`. These can be used to control what part of the world the map shows at any given time. `bounds` will always win over `center`+`zoom`.
- Added another property on the `mapOptions` object: `fitBoundsPadding` that can be used to control the padding in pixels when fitting to bounds.
- Clarified which props are required and which are optional.
> Map as standalone react component: better ways to control world position

- packages/demo-office/src/App.jsx
- packages/demo-office/src/fakeData.js
- packages/demo-office/src/tools/addBlueDot.js
- Implement a "fake" blue dot on the Office demo
- Adds a fake data set that contains a faked device position
- Adds an image created with the Canvas API (copied more or less from the old Vercel demo)
- Adds the faked device position as a data source on the Mapbox map
- Adds a new layer on the Mapbox map using the added data source and the image
- Remove the built-in Position Control from the MIMap since we don't want multiple blue dots
> Demo for offices release 1: fake device position

- package-lock.json
- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/MapTemplate/MapTemplate.jsx
Upgrade SDK version to v4.37.0
> Upgrade SDK version

- packages/map-template/src/components/MapTemplate/MapTemplate.jsx
- packages/map-template/src/components/MapWrapper/MapWrapper.jsx
- packages/map-template/src/hooks/useMapBoundsDeterminer.js
- packages/react-components/src/components/MIMap/MIMap.jsx
- packages/react-components/src/components/MIMap/MapboxMap/MapboxMap.jsx
- packages/react-components/src/components/MIMap/MapboxMap/ViewModeSwitch/ViewModeSwitch.jsx
Make pitch/tilt work properly when resetting (ie. when using the timeout prop). This is reverting an earlier (wrong) decision to include the current pitch when fitting bounds.
However, it causes the same logic (which modules need to be enabled in order to show the viewmode switch) to appear in both the react-components package and now also the map-template package. Any ideas to mitigate this @andreeaceachir142 ?
> Map as standalone component: Fix broken tilt when resetting

- packages/react-components/src/components/MIMap/MapboxMap/ViewModeSwitch/ViewModeSwitch.jsx
fix: wrap the view mode handling in a promise to make sure the MapView is ready. Because if it is not, the calls to hideFeatures will not work (current SDK bug).
> Map as standalone component: Fix timing issue in ViewModeSwitch

- package-lock.json
- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/Search/Search.jsx
- packages/map-template/src/components/Search/Search.scss
- packages/map-template/src/components/Wayfinding/Wayfinding.jsx
- packages/map-template/src/components/Wayfinding/Wayfinding.scss
- packages/map-template/src/i18n/da.js
- packages/map-template/src/i18n/de.js
- packages/map-template/src/i18n/en.js
- packages/map-template/src/i18n/es.js
- packages/map-template/src/i18n/fr.js
- packages/map-template/src/i18n/it.js
- packages/map-template/src/i18n/nl.js
- Update UI on the wayfinding page
- Update the text on the wayfinding page and the placeholder text for the input fields. 
- Update the length of the input fields to only cover 90% 
- Update all translations with the new strings
> Update UI on the wayfinding page

- packages/react-components/src/components/MIMap/MapboxMap/MapboxMap.jsx
Not all file system are case insensitive. This means that on some systems, resolving the ViewModeSwitch component fails because of wrong letter casing.
> fix: casing issue for case sensitive file systems

- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/Search/Categories/Categories.jsx
- packages/map-template/src/components/Search/Search.jsx
---
- Fix issue of clicking outside of MapsIndoors data to close the Categories tab
---
- Implement the usage of the custom hook useOutsideMapsIndoorsDataClick in Categories
- Add a prop to Categories that determines if it is open or not
> Click on non MapsIndoors data to exit categories if active.

- package-lock.json
- packages/map-template/.eslintrc
- packages/map-template/CHANGELOG.md
- packages/map-template/package.json
- packages/react-components/.eslintrc
- packages/react-components/package.json
- Create React App has been deprecated, our projects still contains several dependencies that were originally configured through Create React App. This causes some conflicts with setting up Jest
- Remove Create React App specific ESLint configurations and migrate to standard ESLint rules
> Remove Create React App dependencies

- package-lock.json
- packages/map-template/CHANGELOG.md
- packages/map-template/src/hooks/useMapBoundsDeterminer.js
goTo will not setZoom level, since it fits to bounds
When startZoomLevel is not 18, and is defined in the URL, setCenter to be center of a geometry with a specific zoom level
> Fix: goTo() function refactoring

- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/MapTemplate/MapTemplate.jsx
- packages/map-template/src/components/MapWrapper/MapWrapper.jsx
- Fix 2D/3D selector not respecting the primaryColor query parameter
- Refactor mapOptions by moving the declaration up the dependency tree
- Add a handle function that can be passed down to child components that can add additional values to mapOptions
- Set up primary color prop in mapOptions
> Fix 2D/3D switch not respecting primaryColor prop

- packages/map-template/CHANGELOG.md
- packages/map-template/src/hooks/useMapBoundsDeterminer.js
Fixes bug where wrong map bounds are used when using the `locationId` or `kioskOriginLocationId` props. In those cases, the map should zoom to fit the location.
Introduce the usage of an undefined zoom level when calling `goTo` for the mentioned cases. No zoom level should be used there.
> Fix wrong map bounds when using locationId or kioskOriginLocationId props

- package-lock.json
- packages/map-template/src/hooks/useMapBoundsDeterminer.js
I found out that when startZoomLevel is set to 18, in some cases it is actually is not set to 18 on the map.
It is due to goTo() function that at the end fits venue bounds. 
I removed the check for initialZoomLevel, so:
1. goTo() function will only work when startZoomLevel is not present - meaning that it will panTo venue as usually
2. When startZoomLevel is present in the URL or App.jsx, it will end up in the `else` part of the code.
> bugfix: remove check for initialZoomLevel

- package-lock.json
- packages/map-template/CHANGELOG.md
- packages/map-template/index.html
- packages/map-template/releaseTools/webcomponent.js
- packages/map-template/src/atoms/useAppTitleState.js
- packages/map-template/src/components/MapTemplate/MapTemplate.jsx
- packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx
How: 
- Added useAppTitle prop to all the files necessary, as usual. 
- If `useAppTitle && appConfig` are true we set document.title to App Title, otherwise fallback to default. 
Working solution: 
https://github.com/user-attachments/assets/3d3f0787-42cf-4fde-97e1-584988abb1a4
> Feature: Implement useAppTitle prop

- package-lock.json
- packages/map-template/CHANGELOG.md
- packages/map-template/src/hooks/useMapBoundsDeterminer.js
What:
- I found out that we set zoom level to `undefined` inside goTo() method for kiosk and locationId. It is because if we do not set it to undefined, we will be zoomed out too far from a desired location.
How:
- To fix it, I check if startZoomLevel prop is defined for kiosk or locationId. If it is, I let it zoom in to desired startZoomLevel. Otherwise I keep old functionality. 
Working solution:
https://github.com/user-attachments/assets/b27c5e83-3b17-4d15-965b-cb15ad259b81
> Fix: startZoomLevel not working for kioskOriginLocationId and locationId

- package-lock.json
- packages/components/CHANGELOG.md
- packages/components/package.json
- packages/components/src/components/dropdown/dropdown.tsx
- packages/components/src/components/dropdown/test.html
What:
- It is hard to search for terms like `illy Caffè` using word caffe, because mi-dropdown does not return any results. 
How: 
- Used normalizeText package. 
- It is applied for items in the list and search term so we can find exact matches, without worrying that our keyboard does not support specific symbols/letters.
Testing:
- I added a few test inside components text.html page.
> Feature: Implement normalizeText for mi-dropdown

- packages/map-template/CHANGELOG.md
- packages/map-template/src/App.jsx
- packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx
- packages/map-template/vite.config.js
- Improve sentry error logging
-  Add sentry error boundary around our mapsindoors map component
- Add rule to ignore sdk in error logging
> Add sentry error boundary for map template

- package-lock.json
- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/MapTemplate/MapTemplate.jsx
- packages/map-template/src/hooks/useOnRouteFinished.js
What: There is an issue that when you run the Map Template, change the Venue, create a route and click Finish Route - you would end up in initial Venue (they one that loaded initially)
How: I fixed it by creating a hook that handles onRouteFinished and I used it inside MapTemple.jsx. 
Solution is similar to previous one, but it's simplified. It also covers the issues that Andrei found: https://mapspeople.atlassian.net/browse/SCE-437
> Feature: Fix Finish Route button ending up in initial venue

- packages/map-template/CHANGELOG.md
- packages/map-template/src/hooks/useDirectionsInfo.js
Prevent slower getRoute calls from overtaking faster ones.
In the case of eg. My Position being used, and the position is far away from the current venue, external directions responses can be extremely slow. This had the result of overriding a faster route call then the slow response finally resolved, leading to a sudden jump to an unexpected route.
- Introduced an `isActive` flag to prevent older ones from overtaking. The cleanup function where `isActive` is set to false is always run before the effect runs again.
> Bugfix: Prevent slow getRoute calls from overriding faster ones

- package-lock.json
- packages/map-template/CHANGELOG.md
- packages/map-template/src/components/MapTemplate/MapTemplate.jsx
It was discovered that when there are no tokens present, error message is not shown. 
I made sure to show it once no tokens are present.
> Feature: Set error message when no tokens are present

- packages/map-template/.github/README.md
Clarify the new npm job that is a shortcut for exposing the Map Template on the local network for testing on eg. mobile.
> Docs: Explain how to test on external device
