MapsPeople/web-ui

packages/map-template/public/index.html

I have verified the 3D Models don't blink, and the Solution Config settings are respected (Main Display Rule, Extrusion/Wall opacity).

Upgrade SDK to 4.21.4

---

packages/map-template/src/components/Map/GoogleMapsMap/GooglePlacesHandler.js
packages/map-template/src/components/Wayfinding/Wayfinding.jsx

- Refactor handling of Google Places geometry.
- "DRY"
- Moved the decoration of geometry into the handleGooglePlaces method
- Added a decorateLocation function that runs the handleGooglePlaces method if necessary

refactor: handling of Google Places locations.

---

packages/map-template/src/components/Directions/Directions.jsx
packages/map-template/src/components/Wayfinding/Wayfinding.jsx

- Switch the placement of the wayfinding fields based on UX requirements
- Change the placement of the TO and FROM fields

Feature/switch wayfinding fields 

---

packages/map-template/src/App.jsx

@andreeaceachir142 Do we fall back to a particular Solution if I don't set one? I couldn't find it, but if so, please point out where I need to change that as well 😀

Change Solution to 3D Demo

---

packages/map-template/public/manifest.json

Explanation: https://stackoverflow.com/a/56128412

Add scope to manifest.json

---

packages/components/package.json
packages/map-template/package.json
packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx
packages/map-template/src/index.jsx

Small fixes in preparation for the releases to NPM.

NPM release fixes

---

packages/map-template/README.md
packages/map-template/src/App.jsx
packages/map-template/src/components/Map/Map.jsx
packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx

- Add support for having a `startZoomLevel` property 
- Pass the new property `startZoomLevel` to the `Map` component and make the map react to the changes accordingly

Add support for having "startZoomLevel" property

---

.github/workflows/map-template-bump-version-release.yml

This should fix the failing pipeline here: https://github.com/MapsPeople/web-ui/actions/runs/5118724265/jobs/9203082175

Run Lerna build command before building Map Template

---

README.md

- Align documentation on all the steps for getting started with the Map Template

Align documentation on getting started with the Map Template

---

packages/map-template/CHANGELOG.md
packages/map-template/src/components/Map/Map.jsx

- Remove unwanted visibility of venues and buildings.
- We don't want to show it.

Remove unwanted visibility of venues and buildings

---

packages/map-template/CHANGELOG.md
packages/map-template/src/components/SplashScreen/SplashScreen.scss

Improve the render performance of the animations on the Splash Screen. It appeared to be "janky".
The performance is improved by using a combination of will-change, rotate and transform. This allows the browsers to optimize rendering.

Improve performance of Splash Screen animations

---

packages/map-template/.github/README.md
packages/map-template/CHANGELOG.md

Update README file

---

packages/midt/package.json

Update npm link for midt

---

packages/components/CHANGELOG.md
packages/components/src/components/my-position/my-position.tsx
packages/components/src/utils/utils.ts

The 'Position Dot' on the map is black, it should be blue.
- In the `my-position.tsx` file I deleted the usage of the `getNestedValue` function and replaced it with the default values.
- I also deleted the `getNestedValue` function from the `utils.ts` file

Blue-dot color

---

package-lock.json
packages/components/CHANGELOG.md
packages/map-template/CHANGELOG.md
packages/map-template/src/components/Map/GoogleMapsMap/GoogleMapsMap.jsx
packages/map-template/src/components/Map/MapboxMap/MapboxMap.jsx

Google Maps should also use the new Floor-selector and My-position button Web Components.
The Floor-selector should be positioned below the My-position button.
I added the Web Component to Google Maps and I switched the order of adding these two components to the map.

Position Floor-selector below My-position button

---

package-lock.json
packages/map-template/CHANGELOG.md
packages/map-template/src/components/MapTemplate/MapTemplate.jsx

Upgrade SDK version

---

packages/map-template/CHANGELOG.md
packages/map-template/src/components/Map/Map.jsx

- Fix my position button not working in the wayfinding view
- Add missing `detail` parameter when creating the position control

Fix my position button not working in the wayfinding

---

packages/map-template/src/components/MapTemplate/MapTemplate.jsx
packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx

Refactor the handling of props and query parameters to be the responsibility of the MapsIndoorsMap component.

Handle props and URL params in MapsIndoorsMap component

---

packages/map-template/CHANGELOG.md
packages/map-template/src/components/Map/Map.jsx
packages/map-template/src/components/MapTemplate/MapTemplate.jsx

Upgrade MapsIndoors SDK to newest version and remove behaviour that is now default in the SDK.

Upgrade to MapsIndoors SDK v4.24.4

---

README.md
packages/map-template/.github/README.md
packages/map-template/README.md
packages/map-template/releaseTools/webcomponent.js
packages/map-template/src/App.jsx
packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx

- Update URL parameters docs
- Add docs about query parameters to the README file and include the new prop `supportsURLParameters`
- Rename the `hasURLParameters` to `supportsURLParameters`

Update URL parameters docs

---

packages/map-template/.github/README.md
packages/map-template/README.md

Fix README docs

---

package-lock.json
packages/map-template/CHANGELOG.md
packages/map-template/src/components/Directions/Directions.jsx

- Fixed directions not being shown on mobile 
- Add missing code from resolving the promise when getting mobile bottom padding

Fixed the directions not showing on mobile

---

packages/map-template/.github/README.md
packages/map-template/CHANGELOG.md
packages/map-template/README.md

- Update docs to reflect all the new props added for kiosk

Update docs with kiosk props

---

packages/map-template/CHANGELOG.md
packages/map-template/src/components/QRCodeDialog/QRCodeDialog.jsx

- Fix error when having extra `/` character
- Check if the last character of the pathname is a `/` and remove it

Check for last character of the path name

---

package-lock.json
packages/map-template/CHANGELOG.md
packages/map-template/src/components/MapTemplate/MapTemplate.jsx

- Update SDK version to include the non-selectable and the latest features

Update SDK version

---

packages/map-template/CHANGELOG.md
packages/map-template/src/components/MapTemplate/MapTemplate.jsx

- Add integrity hash to SDK script tag

Add integrity hash to SDK script tag

---

packages/map-template/CHANGELOG.md
packages/map-template/releaseTools/webcomponent.js

- Add missing language prop to web component

Add language prop to web component

---

packages/map-template/CHANGELOG.md
packages/map-template/src/components/MapTemplate/MapTemplate.jsx

Upgrade SDK version.

---

packages/map-template/CHANGELOG.md
packages/map-template/src/components/MapTemplate/MapTemplate.jsx

- Fix a bug where 2D geometry was not always shown.
- The fix is a pure JS SDK fix, so all that's needed is to bump to most recent version.

Fix bug where 2D geometry is not always shown

---

packages/components/CHANGELOG.md
packages/components/src/components.d.ts
packages/components/src/components/dropdown/dropdown.tsx
packages/components/src/components/dropdown/readme.md

I made clearFilter public so I can call it in the CMS

Make clearFilter available

---

package-lock.json
packages/demo-office/package.json
packages/demo-office/src/App.css
packages/demo-office/src/App.jsx
packages/demo-office/src/App.scss
packages/demo-office/src/Search/Search.css
packages/demo-office/src/Search/Search.jsx
packages/demo-office/src/Search/SearchField/SearchField.jsx
packages/demo-office/src/Search/SearchResult/SearchResult.jsx
packages/demo-office/src/fakeData.js

- Implement search functionality in the Office Demo app (nothing yet happens when you click/tap a search results). The search results are also highlighted on the map.
- Implemented Search component that handles searching and presenting search results. 
- Implemented wrapper components around `<mi-search>` and `<mi-list-item-location>`.
Also:
- Extracted all hard coded values into the "fake" data set.
- Extra care given to document the code.

Demo for offices release 1: Search

---

packages/components/CHANGELOG.md
packages/components/src/components.d.ts
packages/components/src/components/dropdown/dropdown.scss
packages/components/src/components/dropdown/dropdown.tsx

I made a few minor changes to the dropdown component.
- Added an alignment attribute to set the dropdown on which side of the button will align. Possible values are left and right, and the default is left. 
- If set the label will be shown as the value in the dropdown button. (Not only for multi-select)

Dropdown enhancements

---

packages/map-template/CHANGELOG.md
packages/react-components/src/components/MIMap/MapboxMap/MapboxMap.jsx

https://github.com/user-attachments/assets/de963f7d-a0b4-4b48-ba62-66bae1e4f898

Add logic to respect miTransitionLevel prop

---

packages/demo-office/index.html
packages/demo-office/src/App.css
packages/demo-office/src/App.jsx
packages/demo-office/src/Header/Header.css
packages/demo-office/src/LocationDetails/LocationDetails.css
packages/demo-office/src/LocationDetails/LocationDetails.jsx
packages/demo-office/src/Search/Search.css
packages/demo-office/src/Search/Search.jsx
packages/demo-office/src/assets/close.svg
packages/demo-office/src/assets/co2.svg
packages/demo-office/src/assets/person.svg
packages/demo-office/src/assets/pin.svg
packages/demo-office/src/assets/thermometer.svg
packages/demo-office/src/hooks/useMediaQuery.js

For the Office demo, show Location details when clicking on a Location 
- Changed breakpoint for larger screens for better alignment with current products
- Refactored markup & styling for the UI component to accommodate the Location details component
- Show details for a Location when clicking on one (either on the map or a search result)
- The Location details for now is just the location name and (for meeting rooms) some mocked measurements
- When clicking on a search result, zoom & pan to the Location on the map
- Implement highlight and selection states

Demo for offices release 1: location details

---

packages/map-template/src/components/LocationDetails/LocationDetails.jsx

- Restructure locationDetails component to follow React best practices
- Identify functions that could use React's useCallback to improve performance
- Move useEffects() before return statement
- Convert the back function to a useCallback

Restructure location details to respect React best practices

---

package-lock.json
packages/map-template/CHANGELOG.md
packages/map-template/src/components/MapTemplate/MapTemplate.jsx

SDK Reference Docs: https://app.mapsindoors.com/mapsindoors/js/sdk/4.39.0/docs/index.html

Feature: Upgrade SDK version

---

packages/map-template/CHANGELOG.md
packages/map-template/src/components/ContactActionButton/ContactActionButton.scss
packages/map-template/src/components/LocationDetails/OpeningHours/OpeningHours.scss

- Fix focus state colors and make text 16px
- Update font sizes for consistency
- Update ContactActionButton hover effect style

Fix focus state colors and text

---

packages/map-template/CHANGELOG.md
packages/map-template/src/components/MapsIndoorsMap/MapsIndoorsMap.jsx

- Map Template would throw errors in the console when using query parameters
- Typecast query parameters to a numerical value to be consistent with the required prop type

Fix query param console error

---

package-lock.json
packages/map-template/CHANGELOG.md
packages/map-template/src/components/MapTemplate/MapTemplate.jsx

- Upgraded SDK version to 4.40.0

Upgraded SDK version

---

packages/map-template/src/components/MapTemplate/MapTemplate.jsx

- Listen for the center value coming from the appConfig
- Update the setCenter useEffect to listen for appConfig changes

Listen for center from appconfig
